INSERT INTO Student (name, groupnumber) VALUES ('John', 1), ('Chris', 1), ('Carl', 1), ('Oliver', 2), ('James', 2), ('Lucas', 2), ('Henry', 2), ('Jacob', 3), ('Logan', 3), ('Albert', 4), ('Betty', 5);
INSERT INTO Subject (name, grade) VALUES ('Art', 1), ('Music', 1), ('Geography', 2), ('History', 2), ('PE', 3), ('Math', 3), ('Science', 4), ('IT', 4), ('Literature', 5), ('Biology', 5);
INSERT INTO PaymentType (name) VALUES ('DAILY'), ('WEEKLY'), ('MONTHLY');
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'John'), (SELECT id FROM PaymentType WHERE name = 'WEEKLY'));
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'Oliver'), (SELECT id FROM PaymentType WHERE name = 'MONTHLY'));
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'Henry'), (SELECT id FROM PaymentType WHERE name = 'WEEKLY'));
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'James'), (SELECT id FROM PaymentType WHERE name = 'DAILY'));
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'Albert'), (SELECT id FROM PaymentType WHERE name = 'MONTHLY'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (8, (SELECT id FROM Student WHERE name = 'Chris'), (SELECT id FROM Subject WHERE name = 'Art'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (5, (SELECT id FROM Student WHERE name = 'Oliver'), (SELECT id FROM Subject WHERE name = 'History'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (9, (SELECT id FROM Student WHERE name = 'James'), (SELECT id FROM Subject WHERE name = 'Geography'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (4, (SELECT id FROM Student WHERE name = 'Jacob'), (SELECT id FROM Subject WHERE name = 'Math'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (9, (SELECT id FROM Student WHERE name = 'Logan'), (SELECT id FROM Subject WHERE name = 'PE'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (6, (SELECT id FROM Student WHERE name = 'Betty'), (SELECT id FROM Subject WHERE name = 'Biology'));