INSERT INTO Student (name, groupnumber) VALUES ('John', 1);
INSERT INTO Student (name, groupnumber) VALUES ('Chris', 1);
INSERT INTO Student (name, groupnumber) VALUES ('Carl', 1);
INSERT INTO Student (name, groupnumber) VALUES ('Oliver', 2);
INSERT INTO Student (name, groupnumber) VALUES ('James', 2);
INSERT INTO Student (name, groupnumber) VALUES ('Lucas', 2);
INSERT INTO Student (name, groupnumber) VALUES ('Henry', 2);
INSERT INTO Student (name, groupnumber) VALUES ('Jacob', 3);
INSERT INTO Student (name, groupnumber) VALUES ('Logan', 3);
INSERT INTO Student (name, groupnumber) VALUES ('Albert', 4);
INSERT INTO Student (name, groupnumber) VALUES ('Betty', 5);
INSERT INTO Subject (name, grade) VALUES ('Art', 1);
INSERT INTO Subject (name, grade) VALUES ('Music', 1);
INSERT INTO Subject (name, grade) VALUES ('Geography', 2);
INSERT INTO Subject (name, grade) VALUES ('History', 2);
INSERT INTO Subject (name, grade) VALUES ('PE', 3);
INSERT INTO Subject (name, grade) VALUES ('Math', 3);
INSERT INTO Subject (name, grade) VALUES ('Science', 4);
INSERT INTO Subject (name, grade) VALUES ('IT', 4);
INSERT INTO Subject (name, grade) VALUES ('Literature', 5);
INSERT INTO Subject (name, grade) VALUES ('Biology', 5);
INSERT INTO PaymentType (name) VALUES ('DAILY');
INSERT INTO PaymentType (name) VALUES ('WEEKLY');
INSERT INTO PaymentType (name) VALUES ('MONTHLY');
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'John'), (SELECT id FROM PaymentType WHERE name = 'WEEKLY'));
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'Oliver'), (SELECT id FROM PaymentType WHERE name = 'MONTHLY'));
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'Henry'), (SELECT id FROM PaymentType WHERE name = 'WEEKLY'));
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'James'), (SELECT id FROM PaymentType WHERE name = 'DAILY'));
INSERT INTO Payment (student_id, type_id) VALUES ((SELECT id FROM Student WHERE name = 'Albert'), (SELECT id FROM PaymentType WHERE name = 'MONTHLY'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (8, (SELECT id FROM Student WHERE name = 'Chris'), (SELECT id FROM Subject WHERE name = 'Art'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (5, (SELECT id FROM Student WHERE name = 'Oliver'), (SELECT id FROM Subject WHERE name = 'History'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (9, (SELECT id FROM Student WHERE name = 'James'), (SELECT id FROM Subject WHERE name = 'Geography'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (4, (SELECT id FROM Student WHERE name = 'Jacob'), (SELECT id FROM Subject WHERE name = 'Math'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (9, (SELECT id FROM Student WHERE name = 'Logan'), (SELECT id FROM Subject WHERE name = 'PE'));
INSERT INTO Mark (mark, student_id, subject_id) VALUES (6, (SELECT id FROM Student WHERE name = 'Betty'), (SELECT id FROM Subject WHERE name = 'Biology'));